const reviews = [
        {
          id: 1,
          ratings:19,
          box:3.5,
          dealers:"Scrap Dealers",
          dealers1:"Scrap Buyers",
          name: "Chauhan Scrap And Dismanting",
          image: "https://imgs.search.brave.com/yCQkEYXjddp0z365BLbllQFhenyN0Bu2a9G-0Yl8v9Q/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9saXJw/LmNkbi13ZWJzaXRl/LmNvbS8wNzgyMDdl/Yy9kbXMzcmVwL211/bHRpL29wdC9kb3du/bG9hZC00LTEwMjR4/NzY4LTEtMTkyMHcu/cG5n",
           loc:"Pancheel Vihar Malviya Nagar , Delhi",
           num:9999999999,
               },
        {
            id: 2,
            ratings:119,
            box:3.9,
            name: "Mishthi Steels",
            dealers:"Scrap Dealers",
            dealers1:"Cardboard Scrap",
            image: "https://imgs.search.brave.com/DgisF3Y3qwCKDTd7TbLmstfx3ExBuu7iiSkpYHGHaik/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9zY3Jh/cG1hbmFnZW1lbnQu/Y29tL3dwLWNvbnRl/bnQvdXBsb2Fkcy8y/MDE4LzExL01SUC05/LTM1MHgzNTAuanBn",
           loc:"Dno 332 Koyla Nagar,Delhi",
           num:9999999999,
        },
        {
          id: 3,
          ratings:200,
          box:4,
          name: "Test Enterprises",
          dealers:"Computer Scrap",
          dealers1:"Plastic Scrap",
          image:" https://imgs.search.brave.com/jSgEonT4BbRciE-MYavJmsr8kONMAnWAz8AQIODkxqI/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5pc3RvY2twaG90/by5jb20vaWQvMTMz/OTkzNjc4L3Bob3Rv/L2Nsb3NlLXVwLXBo/b3RvLW9mLXNpbHZl/ci1jb2xvci1zY3Jh/cC1tZXRhbC1hbmQt/bWV0YWwtdHJhc2gu/anBnP3M9NjEyeDYx/MiZ3PTAmaz0yMCZj/PW9Wa05CdFZNNGdD/VGpOMldsOWw1M2x3/ZDJ1NnVyNDBBOWYy/TGFFSE54MGM9",
          loc:"Ram Nagar Kota , Rajasthan",
          num:9999999999,
        },
        {
          id: 4,
          ratings:500,
          box:4.5,
          dealers:"Steel Scrap ",
          dealers1:"Scrap Buyers",
          name: "Hk Contractor",
          image: "https://imgs.search.brave.com/3Yr0OXkKGsAkLLb0FLSOFHvbetx5Z_gfMgqD_Ab8-3M/rs:fit:860:0:0/g:ce/aHR0cHM6Ly90NC5m/dGNkbi5uZXQvanBn/LzAyLzU3LzYxLzIz/LzM2MF9GXzI1NzYx/MjMwNF9MMXBqbnNt/Mk1mTU5JaFNETzR6/UUFyMkg5V3oyVzlR/aC5qcGc",
          loc:"D-87 Basant Vihar , Delhi",
          num:9999999999,
        },
        {
          id: 5,
          ratings:800,
          box:4.7,
          name: "Shanti Scrap Traders",
          dealers:"Car Scrap",
          dealers1:"Battery Scrap",
          image: "https://imgs.search.brave.com/5md4tqolHulRcGE2po1ABvgBaqrrPJ2n8DK3PcFKvTQ/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL0kv/NzE4d2I5TnRuWUwu/anBn",
          loc:"Lajpat Nagar Market, Chandni Market Delhi",
          num:9999999999,
        },
        {
            id: 6,
            ratings:900,
            box:3.2,
            name: "sheebani Scrap Traders",
            dealers:"Second Hand Buyers",
            dealers1:"Paper Scrap",
            image: "https://content.jdmagicbox.com/comp/pune/p5/020pxx20.xx20.100807105552.y9p5/catalogue/a-g-enterprises-chikhali-pune-e-waste-recycling-q66hpn0zlt-250.jpg",
           loc:"Faridabad Sector-49 , Faridabad",
           num:9999999999,
        },
          {
            id: 7,
            ratings:1500,
            box:3.5,
            name: "mahaveer scrap traders",
            dealers:"Computer Scrap",
            dealers1:"Scrap Buyers",
            image: "https://imgs.search.brave.com/-UKww1OnswTmGcwyPLL0l89MliIXbVAGJTxWHl137Rw/rs:fit:860:0:0/g:ce/aHR0cHM6Ly93d3cu/c2ltc21tLmNvbS93/cC1jb250ZW50L3Vw/bG9hZHMvc2l0ZXMv/My8yMDE4LzA0L21l/dGFsLXNjcmFwLTEw/LnBuZw",
           loc:"Talkies Road Shastri Nagar, Guna",
           num:9999999999,
        },
          {
            id: 8,
            ratings:2000,
            box:2,
            name: "Sheetal Enterprises",
            dealers:"Scrap Dealers",
            dealers1:"Scrap Buyers",
            image: "https://imgs.search.brave.com/jXoJRqEQRI_yvuZIlB7QiE0SbIsSsEl9Kq6tWeQY99M/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9saXJw/LmNkbi13ZWJzaXRl/LmNvbS8wNzgyMDdl/Yy9kbXMzcmVwL211/bHRpL29wdC9kb3du/bG9hZC0xMDI0eDc2/OC0xLTE5MjB3LnBu/Zw",
           loc:"Ab Road Vallabh Nagar , Bhopal",
           num:9999999999,
        },
      ];
      
    export default reviews;